
CREATE DATABASE IF NOT EXISTS movie_db;
CREATE TABLE IF NOT EXISTS movie_db.movie (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    director VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    rating FLOAT NOT NULL CHECK (rating >= 0.0 AND rating <= 10.0),
    synopsis VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
